[build]
    publish = 'output'
    command = 'pip install -r requirements.txt && pelican content -s publishconf.py'

[build.environment]
    PYTHON_VERSION = 3.10

[[redirects]]
    from = '/posts/*'
    to = '/posts/:splat'
    status = 200

[context.production.environment]
    PELICAN_ENV = 'production'
